name: Publish

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: change to ref
        run: git checkout ${{ github.ref_name }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          version: ">=0.5.29"

      - name: Set up Python
        run: uv python install

      - name: Build the project
        run: |
            version=${{ github.ref_name }}
            version=${version#v}
            export SETUPTOOLS_SCM_PRETEND_VERSION=$version
            # from https://github.com/astral-sh/uv/issues/8729#issuecomment-2654619679
            uv lock --check
            cp pyproject.toml pyproject.toml.bak
            cp uv.lock uv.lock.bak
            uv export --locked --no-dev --no-extra pinned --no-hashes --no-emit-workspace --output-file pinned_requirements.txt > /dev/null
            uv add --optional pinned -r pinned_requirements.txt
            uv build
            mv pyproject.toml.bak pyproject.toml
            mv uv.lock.bak uv.lock
            rm -f pinned_requirements.txt

      - name: Publish distribution 
        run: uv publish

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --generate-notes --latest --verify-tag dist/**
